pub mod reformat_the_string;
pub mod check_if_a_word_occurs_as_a_prefix_of_any_word_in_a_sentence;
pub mod string_rotation_lcci;
pub mod reformat_phone_number;
pub mod check_if_binary_string_has_at_most_one_segment_of_ones;
pub mod shortest_common_supersequence;
pub mod masking_personal_information;
pub mod longest_chunked_palindrome_decomposition;
