pub mod check_permutation_lcci_test;
pub mod count_substrings_that_differ_by_one_character_test;
pub mod get_kth_magic_number_lcci_test;
pub mod powerful_integers_test;
pub mod remove_letter_to_equalize_frequency_test;
pub mod valid_anagram_test;
pub mod smallest_integer_divisible_by_k_test;
