pub mod final_prices_with_a_special_discount_in_a_shop;
pub mod min_stack;
pub mod valid_parentheses;
pub mod validate_stack_sequences;
pub mod crawler_log_folder;
pub mod minimum_add_to_make_parentheses_valid;
pub mod shortest_subarray_to_be_removed_to_make_array_sorted;
pub mod next_greater_node_in_linked_list;
pub mod dinner_plate_stacks;
